# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# Command line
# Run a command line script using Bash on Linux and macOS and cmd.exe on Windows

- task: CmdLine@2
  displayName: Configurar o StorSimple
  inputs:
    #script: 'mkdir d:\a\1\MobEAD' 
    script: 'echo StorSimple criado'
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

- task: CmdLine@2
  displayName: Definir permissões
  inputs:
    script: 'echo Permissões adicionadas'

# - task: CmdLine@2
#   displayName: Configurar DNS
#   inputs:
#     script: 'echo DNS configurado'

# - task: CmdLine@2
#   displayName: Configurar VPN Site-to-Site
#   inputs:
#     script: 'echo VPN configurada'